### ISSUE TITLE
Remove/skip old packages

### ISSUE THREAD

**Issue by mmarodin** [angrox/spacewalk-api-scripts#22]
Hi.

There is a way to remove finally old packages from a channel?
I can use spacewalk-remove-old-packages.py script to do it, but after a sync of the channel Spacewalk will download again the same old packages.

There is a way to cheat Spacewalk so it skip them during sync? :)

Please let me know, thanks.
Morgan

**Comment by angrox** [comment]
As written before this is done by spacewalk-repo-sync. One possibilty would be to enhance the repo sync script with a feature only to sync the newest packages. 
A workaround could be that you have your daily sync channels, clone/merge them to a new/other channel and then remove the old packages. But this is a rather cpu intensive operation.
