### ISSUE TITLE
spacewalk-remove-old-packages.py - UnboundLocalError: local variable 'ret' referenced before assignment

### ISSUE THREAD

**Issue by storm49152** [angrox/spacewalk-api-scripts#28]
Running the script I get:

```
Getting all packages without channel
Packages to remove: 11484
Deleting packages from spacewalk (if packages could not be removed they are maybe in another channel too)
Deleting package docker-engine-1.11.2-1.el7.centos (ID: 179245)
  - Could not delete package from Spacewalk
Traceback (most recent call last):
  File "/root/spacewalk-scripts/spacewalk-remove-old-packages.py", line 218, in <module>
    main()
  File "/root/spacewalk-scripts/spacewalk-remove-old-packages.py", line 210, in main
    if ret != 1:
UnboundLocalError: local variable 'ret' referenced before assignment

```

It happens when an "except" is triggered; "ret" is then apparently not assigned, but the "if ret != 1:" line is still executed. Since I guess it only makes sense to execute the "if" line when "ret" is assigned, I moved it into the "try" block.

[spacewalk-remove-old-packages.py.diff.txt](https://github.com/angrox/spacewalk-api-scripts/files/954885/spacewalk-remove-old-packages.py.diff.txt)

**Comment by angrox** [comment]
Can you make a pull request with your diff?

**Comment by storm49152** [comment]
I just created a pull request.

**Comment by angrox** [comment]
Thanks for the bugfix! :-)
